### ISSUE TITLE
Filter on HTTP methods in the redirect plugin

### ISSUE THREAD

**Issue by ludovicm67** [zazuko/trifid-core#6]
In some cases filtering on methods can be required.

I propose that we add a new `methods` key, that is an array, in the redirect plugin configuration.
If it is undefined or empty, it will continue to catch all methods (to keep compatibility with existing configurations).

Here is an example of configuration to redirect all requests on `/query` that uses the `GET` method to `/`:

```json
{
  "redirects": {
    "query": {
      "methods": ["GET"],
      "path": "/query",
      "target": "/"
    }
  }
}
```

File where the plugin is defined: https://github.com/zazuko/trifid-core/blob/master/plugins/redirects.js

**Comment by p1d1d1** [comment]
Any news here?

**Comment by ludovicm67** [comment]
@bergos ping?

**Comment by l00mi** [comment]
@ludovicm67 that will not solve the problem, we want to make it possible to have a GET query with a Parameter using a SPARQL query, only the empty query parameter should not give back the whole db. Also please try to solve this on Fuseki config now as we can configure it. It would be the correct place.

**Comment by ludovicm67** [comment]
> that will not solve the problem

@l00mi For our case, it will solve it.

> we want to make it possible to have a GET query with a Parameter using a SPARQL query, only the empty query parameter should not give back the whole db

Maybe adding an `ignoreQueryParameters` field (default value: `true`) that if sets to `false` will require to have exactly the specified queries parameters.

This will solve the case you mentioned, and still solve our issue.

What's your opinion about this @l00mi and @bergos?

> Also please try to solve this on Fuseki config now as we can configure it. It would be the correct place.

@l00mi if you (or anyone else) find something relevant, I'm fully open.

But I cannot find anything relevant either in the documentation or in the vocab file:
- https://jena.apache.org/documentation/fuseki2/fuseki-configuration.html
- https://github.com/apache/jena/blob/main/jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/server/FusekiVocab.java

So until it's configurable, that's not the correct place.

**Comment by l00mi** [comment]
@ktk can you ask Andy?

**Comment by ludovicm67** [comment]
Good news: it's now fixed.

It was fallbacking to the graph store protocol endpoint (the only one that was working previously before the Assembler was working for GeoSPARQL).
I updated the endpoint and it's now working as expected.
